BEGIN;

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES neon_auth."user"(id) ON DELETE CASCADE,
  email text,
  liked_exercises text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.check_ins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  survival_state text CHECK (survival_state IN ('fight', 'flight', 'freeze', 'fawn', 'safe')),
  pre_score numeric,
  post_score numeric,
  exercises_completed text[] NOT NULL DEFAULT '{}',
  reflection text,
  date date,
  symptoms text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.exercises (
  id text PRIMARY KEY,
  survival_state text NOT NULL CHECK (survival_state IN ('fight', 'flight', 'freeze', 'fawn', 'safe')),
  category text NOT NULL,
  category_emoji text,
  category_order integer NOT NULL,
  exercise_order integer NOT NULL,
  title text NOT NULL,
  duration text,
  type text,
  emoji text,
  description text,
  steps jsonb NOT NULL DEFAULT '[]',
  phases jsonb,
  rounds integer
);

CREATE TABLE public.exercise_videos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  exercise_id text NOT NULL,
  survival_state text CHECK (survival_state IN ('fight', 'flight', 'freeze', 'fawn', 'safe')),
  exercise_title text,
  video_url text NOT NULL,
  video_type text NOT NULL CHECK (video_type IN ('youtube', 'vimeo', 'upload', 'audio', 'image')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.subscriptions (
  user_id uuid PRIMARY KEY REFERENCES neon_auth."user"(id) ON DELETE CASCADE,
  stripe_customer_id text UNIQUE,
  stripe_subscription_id text UNIQUE,
  status text,
  current_period_end timestamptz,
  price_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.symptom_categories (
  id text PRIMARY KEY,
  label text NOT NULL,
  emoji text,
  description text,
  display_order integer NOT NULL
);

CREATE TABLE public.symptoms (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id text NOT NULL REFERENCES public.symptom_categories(id) ON DELETE CASCADE,
  text text NOT NULL,
  fight_score integer NOT NULL DEFAULT 0,
  flight_score integer NOT NULL DEFAULT 0,
  freeze_score integer NOT NULL DEFAULT 0,
  fawn_score integer NOT NULL DEFAULT 0,
  display_order integer NOT NULL
);

CREATE TABLE public.whitelist (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX whitelist_email_lower_idx ON public.whitelist (lower(email));
CREATE INDEX check_ins_user_id_date_idx ON public.check_ins (user_id, date DESC);
CREATE INDEX exercise_videos_survival_state_idx ON public.exercise_videos (survival_state);
CREATE INDEX exercises_survival_state_idx ON public.exercises (survival_state);
CREATE INDEX symptoms_category_id_display_order_idx ON public.symptoms (category_id, display_order);
CREATE INDEX subscriptions_status_idx ON public.subscriptions (status);

CREATE OR REPLACE FUNCTION public.current_user_is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, neon_auth
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM neon_auth."user" AS app_user
    WHERE app_user.id = auth.uid()
      AND app_user.role = 'admin'
      AND COALESCE(app_user.banned, false) = false
  );
$$;

CREATE OR REPLACE FUNCTION public.has_access(check_user_id uuid, check_email text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT COALESCE(
    auth.uid() = check_user_id
    AND lower(COALESCE(auth.jwt() ->> 'email', '')) = lower(check_email)
    AND (
      EXISTS (
        SELECT 1
        FROM public.whitelist AS allowed
        WHERE lower(allowed.email) = lower(check_email)
      )
      OR EXISTS (
        SELECT 1
        FROM public.subscriptions AS subscription
        WHERE subscription.user_id = check_user_id
          AND subscription.status IN ('active', 'trialing')
          AND (
            subscription.current_period_end IS NULL
            OR subscription.current_period_end > now()
          )
      )
    ),
    false
  );
$$;

CREATE OR REPLACE FUNCTION public.handle_new_neon_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO UPDATE
    SET email = COALESCE(public.profiles.email, EXCLUDED.email);
  RETURN NEW;
END;
$$;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.check_ins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exercise_videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.symptom_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.symptoms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whitelist ENABLE ROW LEVEL SECURITY;

CREATE POLICY profiles_select_own ON public.profiles
  FOR SELECT TO authenticated
  USING (id = auth.uid());

CREATE POLICY profiles_insert_own ON public.profiles
  FOR INSERT TO authenticated
  WITH CHECK (id = auth.uid());

CREATE POLICY profiles_update_own ON public.profiles
  FOR UPDATE TO authenticated
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

CREATE POLICY check_ins_select_own ON public.check_ins
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY check_ins_insert_own ON public.check_ins
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY check_ins_update_own ON public.check_ins
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY check_ins_delete_own ON public.check_ins
  FOR DELETE TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY subscriptions_select_own ON public.subscriptions
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY whitelist_select_own ON public.whitelist
  FOR SELECT TO authenticated
  USING (lower(email) = lower(COALESCE(auth.jwt() ->> 'email', '')));

CREATE POLICY exercises_select_authenticated ON public.exercises
  FOR SELECT TO authenticated
  USING (true);

CREATE POLICY exercises_admin_manage ON public.exercises
  FOR ALL TO authenticated
  USING (public.current_user_is_admin())
  WITH CHECK (public.current_user_is_admin());

CREATE POLICY exercise_videos_select_authenticated ON public.exercise_videos
  FOR SELECT TO authenticated
  USING (true);

CREATE POLICY exercise_videos_admin_manage ON public.exercise_videos
  FOR ALL TO authenticated
  USING (public.current_user_is_admin())
  WITH CHECK (public.current_user_is_admin());

CREATE POLICY symptom_categories_select_authenticated ON public.symptom_categories
  FOR SELECT TO authenticated
  USING (true);

CREATE POLICY symptom_categories_admin_manage ON public.symptom_categories
  FOR ALL TO authenticated
  USING (public.current_user_is_admin())
  WITH CHECK (public.current_user_is_admin());

CREATE POLICY symptoms_select_authenticated ON public.symptoms
  FOR SELECT TO authenticated
  USING (true);

CREATE POLICY symptoms_admin_manage ON public.symptoms
  FOR ALL TO authenticated
  USING (public.current_user_is_admin())
  WITH CHECK (public.current_user_is_admin());

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anonymous, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anonymous, authenticated;
REVOKE ALL ON FUNCTION public.current_user_is_admin() FROM PUBLIC, anonymous;
REVOKE ALL ON FUNCTION public.has_access(uuid, text) FROM PUBLIC, anonymous;

GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.check_ins TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.exercises TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.exercise_videos TO authenticated;
GRANT SELECT ON public.subscriptions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.symptom_categories TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.symptoms TO authenticated;
GRANT SELECT ON public.whitelist TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT EXECUTE ON FUNCTION public.current_user_is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_access(uuid, text) TO authenticated;

COMMIT;
