// Each state has categories (ordered). Each category has exercises.
// Users should complete at least 1 from each category, in order.

export const EXERCISES = {
  fight: [
    {
      category: "Activate",
      categoryEmoji: "⚡",
      exercises: [
        {
          id: "fight_activate_1",
          title: "Lion's Breath",
          duration: "2 min",
          type: "breathwork",
          emoji: "🦁",
          description: "Releases pent-up anger and intensity through the breath and face.",
          steps: [
            "Sit comfortably with your hands on your knees.",
            "Take a deep inhale through your nose.",
            "Open your mouth wide, stick out your tongue, and exhale with a 'haaa' sound.",
            "Let your eyes open wide and gaze at the bridge of your nose.",
            "Repeat 3–5 times, as fiercely as feels right.",
          ],
        },
        {
          id: "fight_activate_2",
          title: "Wall Push",
          duration: "2 min",
          type: "movement",
          emoji: "🧱",
          description: "Channels fight energy into resistance, allowing the body to express its activation.",
          steps: [
            "Stand in front of a wall, arms-length away.",
            "Place one foot in front of the other.",
            "Inhale and bring your palms flat on the wall at chest height. then press your hands into the wall with full strength as you exhale.",
            "Exhale, push into the wall from your shoulders.",
            "Release and relax the body.",
            "Repeat 3–5 times.",
          ],
        },
        {
          id: "fight_activate_3",
          title: "Tense and Release",
          duration: "3 min",
          type: "somatic",
          emoji: "💪",
          description: "Uses deliberate muscle tension to complete the fight response cycle.",
          steps: [
            "Sit or stand comfortably.",
            "Inhale fully.",
            "Hold and clench your fists, tighten your jaw, and squeeze every muscle in your body.",
            "Exhale with a sigh and release everything completely.",
            "Notice the wave of relaxation that follows.",
            "Repeat 3–5 times, allowing each release to go deeper.",
          ],
        },
      ],
    },
    {
      category: "Discharge",
      categoryEmoji: "🌀",
      exercises: [
        {
          id: "fight_discharge_1",
          title: "Rolling & Swinging",
          duration: "3 min",
          type: "movement",
          emoji: "🔄",
          description: "Rolls and swings away stored tension through the shoulders, arms and wrists.",
          steps: [
            "Stand with feet hip-width apart.",
            "Slowly roll your shoulder blades back and down, then forward — make big circles.",
            "Continue for 1 minute.",
            "Next, make fists with the hands, and swing the arms up and back.",
            "Exhale, bring the fists down in front of you.",
            "Repeat 3-5 times.",
          ],
        },
        {
          id: "fight_discharge_2",
          title: "Spinal Flexion & Twisting",
          duration: "3 min",
          type: "movement",
          emoji: "🌪️",
          description: "Wrings tension from the spine and core through gentle flexion and rotation.",
          steps: [
            "Stand hips-width distance apart.",
            "Inhale. lift the arms up and arch your back (chest forward, shoulders back).",
            "Exhale, bring arms down and round your back (chin to chest, belly in).",
            "Repeat 3-5 times.",
            "Then bring your hands down and twist gently to the right, and left.",
            "Let each exhale take you a little deeper into the twist.",
          ],
        },
      ],
    },
    {
      category: "Ground",
      categoryEmoji: "🌿",
      exercises: [
        {
          id: "fight_ground_1",
          title: "Acupressure",
          duration: "2 min",
          type: "somatic",
          emoji: "👆",
          description: "Stimulates key pressure points to quickly calm the nervous system.",
          steps: [
            "Find the soft webbing between your thumb and index finger (the 'He Gu' point).",
            "Apply firm pressure with the opposite thumb and hold for 30 seconds.",
            "Breathe slowly as you hold.",
            "Switch hands and repeat.",
            "Next, tap gently under your collarbone with two fingers for 30 seconds.",
            "Notice a softening sensation spread through your body.",
          ],
        },
        {
          id: "fight_ground_2",
          title: "Centering",
          duration: "9 min",
          type: "grounding",
          emoji: "🎯",
          description: "Returns you to your body's centre of gravity and the present moment.",
          steps: [],
        },
      ],
    },
  ],

  flight: [
    {
      category: "Move",
      categoryEmoji: "🏃",
      exercises: [
        {
          id: "flight_move_1",
          title: "Somatic Shaking",
          duration: "3 min",
          type: "movement",
          emoji: "🌀",
          description: "Discharges anxious flight energy through intentional full-body shaking.",
          steps: [
            "Stand with feet hip-width apart.",
            "Gently start bouncing the knees and let your legs start to shake naturally.",
            "Gradually bounce the knees more, so the shake rises up through the hips and belly.",
            "Let any tension drop and melt away.",
            "Increase the intensity if it feels good. Continue for 2–3 minutes.",
            "Very slowly, come back to stillness. Notice your body.",
          ],
        },
        {
          id: "flight_move_2",
          title: "Heel Drops",
          duration: "2 min",
          type: "movement",
          emoji: "👣",
          description: "Grounds flight energy downward through rhythmic heel percussion.",
          steps: [
            "Stand tall with feet hip-width apart.",
            "Rise slowly up onto your tiptoes.",
            "Let your heels drop naturally, don't force it.",
            "Feel the gentle vibration travel up through your legs.",
            "Repeat rhythmically for 2 minutes.",
            "Notice how the vibration begins to settle your nervous system.",
          ],
        },
        {
          id: "flight_move_3",
          title: "Spinal Flexion & Twisting",
          duration: "3 min",
          type: "movement",
          emoji: "🌪️",
          description: "Moves anxious energy through the spine and releases it through rotation.",
          steps: [
            "Stand hips-width distance apart.",
            "Inhale. lift the arms up and arch your back (chest forward, shoulders back).",
            "Exhale, bring arms down and round your back (chin to chest, belly in).",
            "Repeat 3-5 times.",
            "Then bring your hands down and twist gently to the right, and left.",
            "Let each exhale take you a little deeper into the twist.",
          ],
        },
      ],
    },
    {
      category: "Discharge",
      categoryEmoji: "🌊",
      exercises: [
        {
          id: "flight_discharge_1",
          title: "Body Tapping",
          duration: "3 min",
          type: "somatic",
          emoji: "👋",
          description: "Rhythmic tapping sends safety signals through the body.",
          steps: [
            "Start by making a fist with one hand.",
            "Begin tapping on the opposite side of your chest. Move down and up your arm.",
            "Switch hand and repeat on other side.",
            "Bring both fists to tap your chest, pelvis, sacrum, and down your legs.",
            "Work your way back up the body.",
            "Relax the arms and notice where the body feels more alive and present.",
          ],
        },
        {
          id: "flight_discharge_2",
          title: "Inhale–Hold–Exhale",
          duration: "4 min",
          type: "breathwork",
          emoji: "🌬️",
          description: "Uses the extended exhale to activate the parasympathetic brake.",
          steps: [
            "Sit comfortably with your spine supported.",
            "Inhale slowly through the nose for 4 counts.",
            "Hold gently at the top for 4 counts.",
            "Exhale slowly through the mouth for 8 counts.",
            "Repeat for 4 rounds, allowing each exhale to soften a little more.",
          ],
          phases: [
            { name: "INHALE", seconds: 4, label: "Breathe in slowly", detail: "Through your nose, feel your belly expand gently" },
            { name: "HOLD", seconds: 4, label: "Hold", detail: "Let the breath settle at the top" },
            { name: "EXHALE", seconds: 8, label: "Exhale slowly", detail: "Release softly through your mouth" },
          ],
          rounds: 4,
        },
      ],
    },
    {
      category: "Ground",
      categoryEmoji: "🌿",
      exercises: [
        {
          id: "flight_ground_1",
          title: "Acupressure",
          duration: "2 min",
          type: "somatic",
          emoji: "👆",
          description: "Stimulates key pressure points to quickly calm the nervous system.",
          steps: [
            "Find the soft webbing between your thumb and index finger.",
            "Apply firm pressure with the opposite thumb and hold for 30 seconds.",
            "Breathe slowly as you hold.",
            "Switch hands and repeat.",
            "Next, tap gently under your collarbone with two fingers for 30 seconds.",
            "Notice a softening sensation spread through your body.",
          ],
        },
        {
          id: "flight_ground_2",
          title: "Centering",
          duration: "9 min",
          type: "grounding",
          emoji: "🎯",
          description: "Returns you to your body's centre of gravity and the present moment.",
          steps: [],
        },
      ],
    },
  ],

  freeze: [
    {
      category: "Make Space",
      categoryEmoji: "🌅",
      exercises: [
        {
          id: "freeze_make1_1",
          title: "Social Engagement",
          duration: "3 min",
          type: "somatic",
          emoji: "👁️",
          description: "Uses eyes to signal safety and activate the ventral vagal system.",
          steps: [
            "Interlace your fingers and bring your hands behind your head.",
            "Elbows out to the side. Relax the shoulders.",
            "Shift your eyes to look at your right elbow, head stays in the centre.",
            "Stay there for about 1 minute, then bring your eyes to the middle again.",
            "Repeat on the other side.",
          ],
        },
        {
          id: "freeze_make1_2",
          title: "Fascia Stretching",
          duration: "4 min",
          type: "movement",
          emoji: "🕸️",
          description: "Slow, sustained stretching awakens the connective tissue network.",
          steps: [
            "Extend the arms out to the sides, palms face up",
            "Reach the thumbs back behind you, and pinkies facing the ceiling.",
            "Inhale, breathe into the upper chest.",
            "Exhale, reach the thumb a little further back.",
            "Repeat for 2-3 minutes.",
            "Notice any sensations that arise.",
          ],
        },
        {
          id: "freeze_make1_3",
          title: "Butterfly Tapping",
          duration: "3 min",
          type: "somatic",
          emoji: "🦋",
          description: "Bilateral self-tapping to gently reawaken the body.",
          steps: [
            "Cross your arms over your chest so your hands rest on the opposite shoulders.",
            "Close your eyes or soften your gaze downward.",
            "Begin gently tapping your shoulders, alternating left and right.",
            "Breathe slowly and naturally.",
            "Continue for 2–3 minutes, allowing warmth and presence to return.",
            "Let your arms rest and notice how you feel.",
          ],
        },
      ],
    },
    {
      category: "Activate",
      categoryEmoji: "🌬️",
      exercises: [
        {
          id: "freeze_make2_1",
          title: "Spinal Flexion & Twisting",
          duration: "3 min",
          type: "movement",
          emoji: "🌪️",
          description: "Gently mobilises the frozen spine to invite movement back into the body.",
          steps: [
            "Stand hips-width distance apart.",
            "Inhale. lift the arms up and arch your back (chest forward, shoulders back).",
            "Exhale, bring arms down and round your back (chin to chest, belly in).",
            "Repeat 3-5 times.",
            "Then bring your hands down and twist gently to the right, and left.",
            "Let each exhale take you a little deeper into the twist.",
          ],
        },
        {
          id: "freeze_make2_2",
          title: "Silent Scream",
          duration: "2 min",
          type: "somatic",
          emoji: "😮",
          description: "Opens the throat and jaw to release held freeze-response tension.",
          steps: [
            "Make a fist and bring it under your chin.",
            "Inhale throught the nose.",
            "Exhale out the mouth, open your mouth as wide as possible. Pushing your chin into the fist.",
            "Let out a 'silent scream' as you open the mouth wider.",
            "Follow the silent scream all the way until your exhale is complete.",
            "Repeat 2–3 times, noticing the tension leaving the jaw and throat.",
          ],
        },
      ],
    },
    {
      category: "Ground",
      categoryEmoji: "🌿",
      exercises: [
        {
          id: "freeze_ground_1",
          title: "Acupressure",
          duration: "2 min",
          type: "somatic",
          emoji: "👆",
          description: "Stimulates key pressure points to gently activate and calm.",
          steps: [
            "Find the soft webbing between your thumb and index finger.",
            "Apply firm pressure with the opposite thumb and hold for 30 seconds.",
            "Breathe slowly as you hold.",
            "Switch hands and repeat.",
            "Next, tap gently under your collarbone with two fingers for 30 seconds.",
            "Notice a softening sensation spread through your body.",
          ],
        },
        {
          id: "freeze_ground_2",
          title: "Centering",
          duration: "9 min",
          type: "grounding",
          emoji: "🎯",
          description: "Returns you to your body's centre and the present moment.",
          steps: [],
        },
      ],
    },
  ],

  fawn: [
    {
      category: "Support",
      categoryEmoji: "🫂",
      exercises: [
        {
          id: "fawn_support_1",
          title: "Collapse & Self-Hug",
          duration: "3 min",
          type: "somatic",
          emoji: "🤗",
          description: "Allows the body to fully surrender its holding pattern through supported collapse.",
          steps: [
            "Sit comfortably and let your body completely soften.",
            "Allow your shoulders to drop, your head to hang forward.",
            "Let yourself feel the weight of everything you've been carrying.",
            "After a minute, slowly wrap your arms around yourself.",
            "Hug yourself firmly — feel the contact and warmth.",
            "Stay here for 2 minutes, breathing slowly into your own embrace.",
          ],
        },
        {
          id: "fawn_support_2",
          title: "Palms on Face",
          duration: "2 min",
          type: "somatic",
          emoji: "🙌",
          description: "Gentle face-cupping activates the social nervous system and provides warmth.",
          steps: [
            "Rub your palms together to generate warmth.",
            "Cup your warm hands gently over your cheeks and jaw.",
            "Close your eyes and breathe slowly.",
            "Feel the warmth seeping into your face.",
            "Let the muscles of your face soften completely.",
            "Stay for 1–2 minutes, noticing the sense of being held.",
          ],
        },
        {
          id: "fawn_support_3",
          title: "Diaphragm Compression",
          duration: "3 min",
          type: "breathwork",
          emoji: "🫁",
          description: "Firm pressure on the diaphragm helps release deep-held tension.",
          steps: [
            "Sit upright and place both hands on your ribcage.",
            "Apply gentle pressure.",
            "As you inhale, feel your ribs moving up and outward.",
            "As you exhale, sense your ribs moving down.",
            "Continue this rhythm for 2–3 minutes.",
            "Notice the breath becoming fuller and the belly softening.",
          ],
        },
      ],
    },
    {
      category: "Make Space",
      categoryEmoji: "🌅",
      exercises: [
        {
          id: "fawn_space_1",
          title: "Barrel Rolls",
          duration: "3 min",
          type: "movement",
          emoji: "🛢️",
          description: "Full-body rolling resets the nervous system and wakes up proprioception.",
          steps: [
            "Sit in a cross-legged position.",
            "Let your arms rest on your knees.",
            "Begin moving your upper body and pelvis in slow, smooth circular motions.",
            "Inhale as you lean your torso forward, and exhale as you roll your back and lean backward.",
            "After 2–3 minutes, rest and notice your body.",
          ],
        },
        {
          id: "fawn_space_2",
          title: "Social Engagement",
          duration: "2 min",
          type: "somatic",
          emoji: "👁️",
          description: "Slow, intentional eye movements stimulate the vagus nerve and signal safety.",
          steps: [
            "Interlace your fingers and bring your hands behind your head.",
            "Elbows out to the side. Relax the shoulders.",
            "Shift your eyes to look at your right elbow, head stays in the centre.",
            "Stay there for about 1 minute, then bring your eyes to the middle again.",
            "Repeat on the other side.",
          ],
        },
      ],
    },
    {
      category: "Ground",
      categoryEmoji: "🌿",
      exercises: [
        {
          id: "fawn_ground_1",
          title: "Acupressure",
          duration: "2 min",
          type: "somatic",
          emoji: "👆",
          description: "Stimulates key pressure points to calm and restore.",
          steps: [
            "Find the soft webbing between your thumb and index finger.",
            "Apply firm pressure with the opposite thumb and hold for 30 seconds.",
            "Breathe slowly as you hold.",
            "Switch hands and repeat.",
            "Next, tap gently under your collarbone with two fingers for 30 seconds.",
            "Notice a softening sensation spread through your body.",
          ],
        },
        {
          id: "fawn_ground_2",
          title: "Centering",
          duration: "9 min",
          type: "grounding",
          emoji: "🎯",
          description: "Returns you to your body's centre and reconnects you to your own needs.",
          steps: [],
        },
      ],
    },
  ],

  safe: [
    {
      category: "Deepen",
      categoryEmoji: "✨",
      exercises: [
        {
          id: "safe_1",
          title: "Gratitude Breath",
          duration: "4 min",
          type: "breathwork",
          emoji: "✨",
          description: "Expands your window of tolerance and deepens your sense of safety.",
          steps: [
            "Sit comfortably and close your eyes.",
            "Take a few easy breaths to settle in.",
            "On each inhale, think of something you're genuinely grateful for.",
            "On each exhale, let the feeling of gratitude spread through your body.",
            "There's nothing to force — just let warmth arise naturally.",
            "Continue for 8–10 breaths.",
          ],
        },
        {
          id: "safe_2",
          title: "Coherent Breathing",
          duration: "5 min",
          type: "breathwork",
          emoji: "〰️",
          description: "Breathe at 5 breaths per minute to enter optimal heart coherence.",
          steps: [
            "Sit or lie down comfortably.",
            "Inhale slowly for 5 counts.",
            "Exhale slowly for 5 counts.",
            "Keep this rhythm steady — 5 in, 5 out.",
            "Place one hand on your heart and feel it beat.",
            "Continue for 5 minutes.",
          ],
        },
        {
          id: "safe_3",
          title: "Self-Touch Soothe",
          duration: "3 min",
          type: "somatic",
          emoji: "🤲",
          description: "Gentle touch activates oxytocin and deepens your felt sense of safety.",
          steps: [
            "Slowly stroke one arm with the opposite hand.",
            "Use the same pace and pressure you'd offer a loved one.",
            "Move to your face — gently rest your palms on your cheeks.",
            "Cover your eyes softly with cupped hands.",
            "Breathe and notice the warmth.",
            "Whisper or think: 'I am safe. I am here. I am enough.'",
          ],
        },
      ],
    },
  ],
};

// Flatten all exercises for a given state (for backward compat if needed)
export const flattenExercises = (state) =>
  (EXERCISES[state] || []).flatMap((cat) => cat.exercises);
